In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import lightning as L

from lightning import LightningDataModule

In [3]:
import polars as pl

In [110]:
annotations = pl.read_csv("./egyptian_fruit_bat_annotated/Annotations.csv")

In [153]:
import torchaudio

torchaudio.load("/root/animal-communication-source-separation/egyptian_fruit_bat_annotated/files201/121001000840989803.WAV")[0].shape

torch.Size([1, 672592])

In [154]:
torchaudio.__version__

'2.5.1+cu124'

In [139]:
file_info = pl.read_csv("./egyptian_fruit_bat_annotated/FileInfo.csv")

In [148]:
sub_sub

Emitter,File name,File folder,Start sample,End sample
i64,str,str,i64,i64
228,"""121001000840989803.WAV""","""files201""",228173,672592
226,"""121001002340125828.WAV""","""files201""",1,328528
226,"""121001002836480847.WAV""","""files201""",1,648016
226,"""121001005135085025.WAV""","""files201""",1,992080
226,"""121001005140761026.WAV""","""files201""",1,525136
…,…,…,…,…
208,"""140219073454496420.WAV""","""files224""",1,328528
207,"""140219085552689425.WAV""","""files224""",1,1229648
208,"""140219115758154436.WAV""","""files224""",1,598864


In [144]:
file_info.columns

['FileID',
 'Treatment ID',
 'File name',
 'File folder',
 'Recording channel',
 'Recording time',
 'Voice start sample (1)',
 'Voice end sample (1)',
 'Voice start sample (2)',
 'Voice end sample (2)',
 '...',
 '..._duplicated_0',
 '..._duplicated_1',
 '..._duplicated_2',
 '..._duplicated_3',
 '..._duplicated_4',
 '..._duplicated_5',
 '..._duplicated_6',
 '..._duplicated_7',
 '..._duplicated_8',
 '..._duplicated_9',
 '..._duplicated_10',
 '..._duplicated_11',
 '..._duplicated_12',
 '..._duplicated_13',
 '..._duplicated_14',
 '..._duplicated_15',
 '..._duplicated_16',
 '..._duplicated_17',
 '..._duplicated_18',
 '..._duplicated_19',
 '..._duplicated_20',
 '..._duplicated_21',
 '..._duplicated_22',
 '..._duplicated_23',
 '..._duplicated_24',
 '..._duplicated_25',
 '..._duplicated_26',
 '..._duplicated_27',
 '..._duplicated_28',
 '..._duplicated_29',
 '..._duplicated_30',
 '..._duplicated_31',
 '..._duplicated_32',
 '..._duplicated_33',
 '..._duplicated_34',
 '..._duplicated_35',
 '..._d

In [142]:
file_info.filter(
    pl.col("File name") == "121001000840989803.WAV"
)

FileID,Treatment ID,File name,File folder,Recording channel,Recording time,Voice start sample (1),Voice end sample (1),Voice start sample (2),Voice end sample (2),...,..._duplicated_0,..._duplicated_1,..._duplicated_2,..._duplicated_3,..._duplicated_4,..._duplicated_5,..._duplicated_6,..._duplicated_7,..._duplicated_8,..._duplicated_9,..._duplicated_10,..._duplicated_11,..._duplicated_12,..._duplicated_13,..._duplicated_14,..._duplicated_15,..._duplicated_16,..._duplicated_17,..._duplicated_18,..._duplicated_19,..._duplicated_20,..._duplicated_21,..._duplicated_22,..._duplicated_23,..._duplicated_24,..._duplicated_25,…,_duplicated_152,_duplicated_153,_duplicated_154,_duplicated_155,_duplicated_156,_duplicated_157,_duplicated_158,_duplicated_159,_duplicated_160,_duplicated_161,_duplicated_162,_duplicated_163,_duplicated_164,_duplicated_165,_duplicated_166,_duplicated_167,_duplicated_168,_duplicated_169,_duplicated_170,_duplicated_171,_duplicated_172,_duplicated_173,_duplicated_174,_duplicated_175,_duplicated_176,_duplicated_177,_duplicated_178,_duplicated_179,_duplicated_180,_duplicated_181,_duplicated_182,_duplicated_183,_duplicated_184,_duplicated_185,_duplicated_186,_duplicated_187,_duplicated_188
i64,i64,str,str,i64,str,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,…,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str,str
53480,9,"""121001000840989803.WAV""","""files201""",3,"""2012-10-01 00:08:45""",53673,78773,92677,134419,153673,221419,228173,284419,299301,340419,355708,388780,402673,411919,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,…,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null


In [105]:
better_annotations = pl.read_csv("./egyptian_fruit_bat_annotated/better_annotations.csv")

In [145]:
sub = better_annotations.select(
    [
        pl.col("Emitter"),
        pl.col("File name"),
        pl.col("File folder"),
        pl.col("Start sample"),
        pl.col("End sample"),
    ]
).filter(
    pl.col("Emitter") > 0
)

In [146]:
sub_sub.select(
            pl.col("Start sample")
        ).to_torch().ravel()

tensor([228173,      1,      1,  ...,      1,      1,      1])

In [147]:
sub_sub = sub.filter(
    pl.col("Emitter").is_in([215, 231, 211, 216, 230, 220, 210, 226, 221, 207, 228, 208])
)

In [130]:
sub_sub

Emitter,File name,File folder,Start sample
i64,str,str,i64
228,"""121001000840989803.WAV""","""files201""",228173
226,"""121001002340125828.WAV""","""files201""",1
226,"""121001002836480847.WAV""","""files201""",1
226,"""121001005135085025.WAV""","""files201""",1
226,"""121001005140761026.WAV""","""files201""",1
…,…,…,…
208,"""140219073454496420.WAV""","""files224""",1
207,"""140219085552689425.WAV""","""files224""",1
208,"""140219115758154436.WAV""","""files224""",1


In [131]:
sub_sub.write_csv("./egyptian_fruit_bat_annotated/annotations.csv")

In [73]:
sub_sub

Emitter,File name,File folder
i64,str,str
228,"""121001000728041793.WAV""","""files201"""
228,"""121001000733958794.WAV""","""files201"""
228,"""121001000740457796.WAV""","""files201"""
228,"""121001000744199797.WAV""","""files201"""
228,"""121001000754583800.WAV""","""files201"""
…,…,…
208,"""140219102458100432.WAV""","""files224"""
208,"""140219115758154436.WAV""","""files224"""
207,"""140219115800624437.WAV""","""files224"""


In [134]:
sub_sub["Emitter"].value_counts().filter(
    pl.col("Emitter").is_in([215, 231, 211, 216, 230, 220, 210, 226, 221, 207, 228, 208])
).select(
    (1 / (pl.col("count") / pl.col("count").sum())).sqrt()
).to_numpy().ravel()

array([2.86805807, 3.47640522, 4.64740719, 5.87525434, 2.09101835,
       4.34245812, 4.24390347, 5.9287711 , 4.03328559, 2.96875458,
       3.41184593, 3.26400433])

In [60]:
sub["Emitter"].value_counts().select(
    pl.col("Emitter").gather(pl.arg_sort_by("count"))
).to_numpy().ravel()[::-1][:12]

array([215, 231, 211, 216, 230, 220, 210, 226, 221, 207, 228, 208])

In [52]:
sub["Emitter"].value_counts().arg_sort_by("count")

AttributeError: 'DataFrame' object has no attribute 'arg_sort_by'

In [ ]:
chosen = better_annotations.select(
    [
        pl.col("Emitter").abs(),
        pl.col("File name"),
        pl.col("File folder")
    ]
).filter(
    pl.col("Emitter") != 0
)["Emitter"].value_counts()["count"].arg_sort().to_numpy()

In [97]:
import timm

timm.list_models(filter="efficientvit*")

['efficientvit_b0',
 'efficientvit_b1',
 'efficientvit_b2',
 'efficientvit_b3',
 'efficientvit_l1',
 'efficientvit_l2',
 'efficientvit_l3',
 'efficientvit_m0',
 'efficientvit_m1',
 'efficientvit_m2',
 'efficientvit_m3',
 'efficientvit_m4',
 'efficientvit_m5']

In [85]:
sub_sub.select(
    [
        pl.col("Emitter").rank("dense") - 1
    ]
).to_torch().ravel().unique()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
sub_sub.select(
    [
        pl.col("Emitter").rank("dense") - 1
    ]
)["Emitter"].value_counts().select(
    ((pl.col("count") / pl.col("count").sum()))
).to_numpy().ravel()

array([0.09512988, 0.05223435, 0.04412301, 0.04943105, 0.05450685,
       0.06348074, 0.20736158, 0.06646651, 0.04078891, 0.10217961,
       0.1219852 , 0.10231231])

In [32]:
labels.unique()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40])

In [12]:
better_annotations

,FileID,Emitter,Addressee,Context,Emitter pre-vocalization action,Addressee pre-vocalization action,Emitter post-vocalization action,Addressee post-vocalization action,Start sample,End sample,File name,File folder
i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,i64,str,str
0,7,118,0,9,2,2,3,3,1,336720,"""120601002132055008.WAV""","""files101"""
1,11,0,0,11,0,0,0,0,1,787280,"""120601002344862013.WAV""","""files101"""
2,12,118,0,12,2,2,3,3,1,566096,"""120601003734539035.WAV""","""files101"""
3,15,0,0,12,0,0,0,0,1,402256,"""120601004402612052.WAV""","""files101"""
4,20,0,0,12,0,0,0,0,1,394064,"""120601005147813084.WAV""","""files101"""
…,…,…,…,…,…,…,…,…,…,…,…,…
91075,293223,-208,-221,4,2,2,3,3,1,877392,"""140219102458100432.WAV""","""files224"""
91076,293230,208,221,12,2,2,3,3,1,598864,"""140219115758154436.WAV""","""files224"""
91077,293232,207,221,12,2,2,3,3,1,336720,"""140219115800624437.WAV""","""files224"""


In [97]:
from src.data.bats_datamodule import BatsDataModule

In [106]:
data = BatsDataModule(
    data_dir="/Users/ivanr/diploma/animal-communication-source-separation/datasets/egyptian_fruit_bats",
    audio_fname="audio",
    annotations_fname="annotations.csv",
)

In [107]:
data.setup()

In [108]:
train = data.train_dataloader()

In [109]:
len(train)

125

In [ ]:
df.with_columns(
    pl.col("Color").rank("dense") - 1
)

In [110]:
for x, y in train:
    print(x.shape, y.shape)
    print(y)
    break

torch.Size([64, 3, 256, 257]) torch.Size([64])
tensor([220, 111, 215, 220, 226, 215, 216, 216, 228, 216, 231, 230, 111, 210,
        231, 211, 111, 216, 111, 231, 210, 220, 231, 216, 210, 220, 226, 216,
        211, 230, 210, 228, 226, 216, 220, 111, 228, 215, 228, 210, 111, 215,
        216, 230, 226, 215, 216, 211, 230, 231, 230, 230, 228, 226, 216, 211,
        228, 220, 226, 215, 111, 228, 230, 210])


In [72]:
torchaudio.load("/Users/ivanr/diploma/animal-communication-source-separation/datasets/egyptian_fruit_bats/audio/10056.wav")[0].shape

torch.Size([1, 410447])

In [111]:
annotations = pl.read_csv("/Users/ivanr/diploma/animal-communication-source-separation/datasets/egyptian_fruit_bats/annotations.csv")

In [121]:
annotations.select(
    [
        pl.col("Emitter").rank("dense") - 1
    ]
).to_torch().ravel()

tensor([4, 3, 4,  ..., 0, 0, 0])

In [112]:
annotations

Emitter,File Name
i64,str
216,"""69809.wav"""
215,"""71889.wav"""
216,"""46690.wav"""
230,"""85411.wav"""
215,"""45609.wav"""
…,…
111,"""33297.wav"""
111,"""26880.wav"""
111,"""24407.wav"""


In [8]:
annotations.select(
    [
        pl.col("Emitter").unique_counts(),
    ]
)

Emitter
u32
1000
1000
1000
1000
1000
1000
1000
1000
1000
